### ISSUE TITLE
pip install is not working

### ISSUE THREAD

**Issue by m30m** [snap-stanford/snap-python#111]
When I try to install snap with the following command:
`pip install snap-stanford`
I get the following error:
```
ERROR: Could not find a version that satisfies the requirement snap-stanford (from versions: none)
```

I believe there is a problem with the `pkg_version` variable in `setup.py`.
```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py:364: UserWarning: The version specified ('5.0.0-dev-macosx10.14-x64-py3.6') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

**Comment by roks** [comment]
What is your macOS version and which Python are you using? In general, our prebuilt packages on macOS require Python 3.7, so I suggest an upgrade of your Python 3.6.

**Comment by Lucaslhm** [comment]
This same issue occurs for me. Running Python 3.7.6 in Windows 10.

**Comment by Antoine-H** [comment]
Same issue here. Python 3.8.2 on archlinux
`ERROR: Could not find a version that satisfies the requirement snap-stanford (from versions: none)
ERROR: No matching distribution found for snap-stanford
`

**Comment by wizmer** [comment]
Why is this ticket closed ? It seems the issue has not been resolved.

**Comment by roks** [comment]
This issue was closed, because it was about Python 3.6 on macOS. Other comments were added later and concern other OSs.

**Comment by arnobde** [comment]
Try pip install snap

**Comment by dheeman00** [comment]
Is pip install snap the same thing as snap-stanford

**Comment by wizmer** [comment]
No. Snap has nothing to do with it:
https://pypi.org/project/snap/

While snap-standford is:
https://pypi.org/project/snap-stanford/

**Comment by arnobde** [comment]
Yeah Sorry .. my apologies 'snap' and 'snap-stanford' are different indeed.

**Comment by fgnm** [comment]
I've solved in Windows 10 by installing Python 3.7.8 becuase with 3.7.2 does not works.

**Comment by sansri264** [comment]
Is this thread being continued elsewhere? The issue is not resolved.

**Comment by eft28** [comment]
same here, using Python 3.6.5 in PyCharm/Windows 10

**Comment by CristinBSE** [comment]
same on Python 3.10.2, Windows 10

**Comment by fastle** [comment]
same on Python 3.10.5, Windows 10

**Comment by RishavDaredevil** [comment]
same has anyone got a solution?

**Comment by pluieciel** [comment]
on google colab, Python 3.10.12
! pip install snap-stanford
ERROR: Could not find a version that satisfies the requirement snap-stanford (from versions: none)
ERROR: No matching distribution found for snap-stanford

----

snap need Python3.7
in Google Colab, try:

%%capture
! sudo apt-get install python3.7
! sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
! sudo update-alternatives --config python3
! sudo apt install python3-pip
! sudo apt install python3.7-distutils
! python -m pip install snap-stanford
import sys
sys.path.append("/usr/local/lib/python3.7/dist-packages/")
import snap

**Comment by vitorgtomaz** [comment]
On windows 10, I changed my kernel from python 3.11.X to 3.9.X and it worked. Probably some compatibility issue?

**Comment by godblessourdeadkotatsu** [comment]
Same error for python 3.13
